#!/usr/bin/zsh

export HISTFILE=~/.zsh_history.66085217
export HISTSIZE=50000
export SAVEHIST=50000

# fixa inkonsekvens mellan solaris/linux
if [[ "${HOSTNAME}x" == "x" ]] ; then
    HOSTNAME=$HOST
fi

# ifall zsh kors utan screen. 
oscreen() {
    precmd () { print -Pn "\e]0;[%n@%M]%# [%~]\a" }
    preexec () { print -Pn "\e]0;[%n@%M]%# [%~] ($1)\a" }

}

medscreen() {
#    unset DISPLAY

    preexec () {
	local CMD=`echo $1 | cut -d " " -f1`
	local host=${HOSTNAME//companioncube/cc}
	echo -ne "\ek$USER@$host:$CMD\e\\"
    }
    precmd() {
	local host=${HOSTNAME//companioncube/cc}
	echo -ne "\ek$USER@$host\e\\"
    }
}

# Default så körs medscreen..
if [[ $TERM == "screen" ]] ; then
    medscreen
else
    oscreen
fi

# ändra termen till xterm om det körs via cygwin.
if [[ $TERM == "cygwin"  || $TERM == "vt100" ]] ; then
    print "Changing term from $TERM to xterm"
    export TERM="xterm"
fi


# Hosts ( for completion )
hosts=( sadbprodlogin1 sadbsatlogin1 sadbprodwls1 sadbsatwls1 sadburawls sadbsatapp7 sadbverifapp9 sadburaapp5 sadbteknikopa5 sadbprodwlsmgmg1 )

# Set/unset  shell options

bindkey -e                 # emacs key bindings
bindkey ' ' magic-space    # also do history expansion on space


autoload -U compinit compinit
setopt autopushd pushdminus pushdsilent pushdtohome
setopt autocd
setopt cdablevars
setopt ignoreeof
setopt interactivecomments
setopt nobanghist
setopt noclobber
setopt HIST_REDUCE_BLANKS
setopt HIST_IGNORE_SPACE
setopt SH_WORD_SPLIT
setopt nohup

##################################################################
# Stuff to make my life easier

# allow approximate
zstyle ':completion:*' completer _complete _match _approximate
zstyle ':completion:*:match:*' original only
zstyle ':completion:*:approximate:*' max-errors 1 numeric

# tab completion for PID :D
zstyle ':completion:*:*:kill:*' menu yes select
zstyle ':completion:*:kill:*' force-list always

# cd not select parent dir
zstyle ':completion:*:cd:*' ignore-parents parent pwd

# useful for path editing  backward-delete-word, but with / as additional delimiter
backward-delete-to-slash () {
  local WORDCHARS=${WORDCHARS//\//}
  zle .backward-delete-word
}
zle -N backward-delete-to-slash

##################################################################
# Key bindings
# http://mundy.yazzy.org/unix/zsh.php
# http://www.zsh.org/mla/users/2000/msg00727.html

typeset -g -A key
bindkey '^?' backward-delete-char
bindkey '^[[1~' beginning-of-line
bindkey '^[[5~' up-line-or-history
bindkey '^[[3~' delete-char
bindkey '^[[4~' end-of-line
bindkey '^[[6~' down-line-or-history
bindkey '^[[A' up-line-or-search
bindkey '^[[D' backward-char
bindkey '^[[B' down-line-or-search
bindkey '^[[C' forward-char 
# Detta funkar inte...
bindkey '^[w' backward-delete-to-slash
# completion in the middle of a line
bindkey '^i' expand-or-complete-prefix


# fkappl/wdp
sh_source() {
    emulate -L sh
    source "$@"
  }

if [[ -f $HOME/.alias ]] ; then
        sh_source $HOME/.alias
fi
if [[ $USER = wdp[0-9][0-9][0-9]* ]] ; then
        sh_source ~/.profile
fi

setprompt () {
	# load some modules
	autoload -U colors zsh/terminfo # Used in the colour alias below
	colors
	setopt prompt_subst

       PROMPT="#[%n@%m]-[%D{%a %y-%m-%d} %*]-[%(?.%{$fg_bold[white]%}.%{$fg_bold[red]%})%?%{$reset_color%}]
#%2c%# "
}

setprompt

## Defines

MHOME=/home/mickevi
export EDITOR="emacs"

# generlla aliases 


export PATH=/usr/bin/:${PATH}:${MHOME}/local-linux/bin:~/bin:${MHOME}/bin
export LD_LIBRARY_PATH=$MHOME/local-linux/lib
alias ls="ls -F --color"


alias grep="grep --color"
alias egrep="egrep --color"
ediff-emacs() {
	    /usr/bin/emacs -eval "(ediff-files \"$1\" \"$2\")"
}
# Git:
export GIT_AUTHOR_NAME="Mikael Viklund"
export GIT_AUTHOR_EMAIL="mickevi@gmail.com"
export GIT_COMMITTER_NAME="Mikael Viklund"
export GIT_COMMITTER_EMAIL="mickevi@gmail.com"
export EMAIL="mickevi@gmail.com"

unset  LANG
export LC_CTYPE="sv_SE.UTF-8"
export LC_NUMERIC="sv_SE.UTF-8"
export LC_TIME="sv_SE.UTF-8"
export LC_COLLATE="sv_SE.UTF-8"
export LC_MONETARY="sv_SE.UTF-8"
export LC_MESSAGES=C
export LC_PAPER="sv_SE.UTF-8"
export LC_NAME="sv_SE.UTF-8"
export LC_ADDRESS="sv_SE.UTF-8"
export LC_TELEPHONE="sv_SE.UTF-8"
export LC_MEASUREMENT="sv_SE.UTF-8"
export LC_IDENTIFICATION="sv_SE.UTF-8"

